### ISSUE TITLE
Getting error while running collections from Jenkins

### ISSUE THREAD

**Issue by encharaananthamurthy** [postmanlabs/newman#1087]
1. Newman Version (can be found via `newman -v`): 3.7.0
 2. OS details (type, version, and architecture): Linux fe-webCOSbuild 2.6.32-642.el6.x86_64
CentOS release 6.8 (Final)
 3. Are you using Newman as a library, or via the CLI? CLI
 3. Did you encounter this recently, or has this bug always been there: recently
 4. Expected behaviour: newman collections should work on jenkins without hitting the issue
 5. Command / script used to run Newman: newman run /jenkins/collection.json -e /jenkins/environment.json 
 6. Sample collection, and auxilliary files (minus the sensitive details):
```
	"variables": [],
	"info": {
		"name": "xyz",
		"_postman_id": "123",
		"description": "",
		"schema": "https://schema.getpostman.com/json/collection/v2.0.0/collection.json"
	},
	"item": [
		{
			"name": "abc",
			"description": "",
			"item": [
				{
					"name": "abc",
					"event": [
						{
							"listen": "abc",
							"script": {
								"type": "text/javascript",
								"exec": [
									"tests[\"Status code is 200\"] = responseCode.code === 200;",
									"",
									"var jsonData = JSON.parse(responseBody);",
									"if(jsonData.data.id === 1) { //Admin",
									"    tests[\"Correct Username\"] = jsonData.data.username === \"xyz@abc.com\"",
									"}",
									"else if(jsonData.data.id === 2) { //Customer",
									"    tests[\"Correct Username\"] = jsonData.data.username === \"def@abc.com\"",
									"}",
									"",
									"tests[\"Has Profile\"] = jsonData.data.profile.data.full",
									""
								]
							}
						}
					],
					"request": {
						"url": "http://{{url}}/v{{version}}/abc",
						"method": "GET",
						"header": [
							{
								"key": "Content-Type",
								"value": "application/json",
								"description": ""
							},
							{
								"key": "Authorization",
								"value": "Bearer {{token}}",
								"description": ""
							},
							{
								"key": "X-Requested-With",
								"value": "XMLHttpRequest",
								"description": ""
							}
						],
						"body": {
							"mode": "raw",
							"raw": "{\n  \"email\": \"def@abc.com\"\n}"
						},
						"description": ""
					},
					"response": []
				},
```
Error message
```
/usr/local/lib/node_modules/newman/bin/newman.js:29
process.version[1]) >= 6) && [process.stdout, process.stderr].forEach((s) => {
                                                                           ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3
```
Build step 'Execute shell' marked build as failure
Finished: FAILURE

**Comment by DominicGunn** [comment]
This looks like the authentication issue under investigation [here. (1085)](https://github.com/postmanlabs/newman/issues/1085)

**Comment by czardoz** [comment]
This is not the authentication issue, @DominicGunn (it's a SyntaxError, and there's no auth information in the OP's collection)/

@encharaananthamurthy Seems that you are using an old version of Node, which does not support arrow functions, maybe try updating to a newer version?

**Comment by encharaananthamurthy** [comment]
@czardoz I am in the node version v7.6.0
 I will upgrade and let you know.
Thanks for the response

**Comment by encharaananthamurthy** [comment]
@czardoz I have updated the Node and now I am able to run the script.
Thanks so much for the help!
