### ISSUE TITLE
Error: this is not a typed array

### ISSUE THREAD

**Issue by shankyty** [postmanlabs/newman#1102]
[This change is introduced in version 6](https://github.com/postmanlabs/newman/commit/f86a9efb92ef92dcb058fe93995861452f25c1d5)

Please refer [this](https://nodejs.org/api/buffer.html#buffer_buffer)

Hence need to upgrade node version in package.json

**Comment by shankyty** [comment]
Issue in java
TypeError: this is not a typed array.
    at Function.from (native)
    at /home/shashankt/repo/regression/node_modules/newman/lib/reporters/html/index.js:79:65
    at /home/shashankt/repo/regression/node_modules/newman/node_modules/lodash/lodash.js:13767:16
    at arrayEach (/home/shashankt/repo/regression/node_modules/newman/node_modules/lodash/lodash.js:537:11)
    at Function.transform (/home/shashankt/repo/regression/node_modules/newman/node_modules/lodash/lodash.js:13766:43)
    at EventEmitter.<anonymous> (/home/shashankt/repo/regression/node_modules/newman/lib/reporters/html/index.js:60:28)
    at EventEmitter.emit (/home/shashankt/repo/regression/node_modules/newman/node_modules/eventemitter3/index.js:151:33)
    at _.assignIn.done (/home/shashankt/repo/regression/node_modules/newman/lib/run/index.js:221:29)
    at /home/shashankt/repo/regression/node_modules/newman/node_modules/postman-runtime/lib/backpack/index.js:56:34
    at PostmanCollectionRun._.assign._process (/home/shashankt/repo/regression/node_modules/newman/node_modules/postman-runtime/lib/runner/run.js:133:20)

**Comment by shankyty** [comment]
https://github.com/postmanlabs/newman/pull/1103

**Comment by kunagpal** [comment]
@shankyty Thanks for reporting this. Could you also mention the exact Node version?

**Comment by kunagpal** [comment]
@shankyty A fix for this bug has been added in #1105, and will be rolled out with the next Newman release.
