### ISSUE TITLE
Newman is incompatable with newest versions of 

### ISSUE THREAD

**Issue by tichiyasu** [postmanlabs/newman#146]
Newman does not support the newest versions of node.js and npm. The newest version of node.js that seems to work is v0.10.29 with npm v1.4.14. When attempting to call newman with the newest versions, the following error is returned.

```
[root@myuser]# newman -h
/usr/local/lib/node_modules/newman/node_modules/jsdom-nogyp/lib/jsdom/level1/core.js:554
      Array.prototype.splice.call(this._childNodes, refChildIndex, 0, newChild
                             ^
TypeError: Cannot set property length of [object Object] which has only a getter
    at Object.core.Node.insertBefore (/usr/local/lib/node_modules/newman/node_modules/jsdom-nogyp/lib/jsdom/level1/core.js:554:30)
    at Object.<anonymous> (/usr/local/lib/node_modules/newman/node_modules/jsdom-nogyp/lib/jsdom/level2/events.js:314:20)
    at Object.proto.(anonymous function) [as insertBefore] (/usr/local/lib/node_modules/newman/node_modules/jsdom-nogyp/lib/jsdom/utils.js:23:26)
    at Object.core.Node.appendChild (/usr/local/lib/node_modules/newman/node_modules/jsdom-nogyp/lib/jsdom/level1/core.js:672:17)
    at /usr/local/lib/node_modules/newman/node_modules/jquery/dist/jquery.js:4006:18
    at /usr/local/lib/node_modules/newman/node_modules/jquery/dist/jquery.js:4026:3
    at module.exports (/usr/local/lib/node_modules/newman/node_modules/jquery/dist/jquery.js:31:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/newman/src/utilities/PreRequestScriptProcessor.js:6:48)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

**Comment by SamvelRaja** [comment]
I am using node v0.11.14 and npm 2.0.0   

Me too facing the same error.  Anyone having the same problem ?

**Comment by abhijitkane** [comment]
I'm using the latest versions of node (0.10.36) and npm (2.4.1), and Newman is working fine for me.

http://puu.sh/fqGix.png

**Comment by SamvelRaja** [comment]
Thanks @abhijitkane  its working fine with (0.10.36 - Officially updated node version ). Most of our build tools using the more advanced version of node. That's why i faced the issue.
