### ISSUE TITLE
Jenkin Pipeline for Postman test using Newman is not successful

### ISSUE THREAD

**Issue by saranyal** [postmanlabs/newman#1530]
Hi there,

I have a postman collection which I am successfully able to run in newman. I wanted to create a Jenkins pipeline on a Windows machine and followed the Blogpost under Postman site but I am facing error while building the project in Jenkins.

So, this is what the command I use to run the collection via newman:

**newman run Test.postman_collection.json -e Stage-Test.postman_environment.json --insecure --no-color**

So under Jenkins project , gave the following command under "Build Shell" script

newman -c C:\workspaces\APITesting\Test.postman_collection.json -e C:\workspaces\APITesting\Stage-Test.postman_environment.json --exitCode 1

But when I build the project, receiving the following error:

Building in workspace C:\Program Files (x86)\Jenkins\workspace\Test
[Test] $ sh -xe C:\WINDOWS\TEMP\jenkins4613443500984257823.sh
The system cannot find the file specified
FATAL: command execution failed
java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
Caused: java.io.IOException: Cannot run program "sh" (in directory "C:\Program Files (x86)\Jenkins\workspace\Test"): CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(Unknown Source)
	at hudson.Proc$LocalProc.<init>(Proc.java:249)
	at hudson.Proc$LocalProc.<init>(Proc.java:218)
	at hudson.Launcher$LocalLauncher.launch(Launcher.java:929)
	at hudson.Launcher$ProcStarter.start(Launcher.java:449)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:109)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:66)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1794)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'Execute shell' marked build as failure
Finished: FAILURE

Any help on this will be much appreciated.

Thanks
Saranya

**Comment by kunagpal** [comment]
@saranyal This appears to be independent of Newman, as the shell script driver is missing. You can confirm this by running `where sh` on the build machine, which will result in the global path to `sh` being returned, or an error if `sh` can't be found. You can also confirm that Newman is installed by running `where newman` for the sake of completeness.

**Comment by saranyal** [comment]
Thanks
I did the following and it worked.

C:\Users\saranya\AppData\Roaming\npm\newman -c "C:\\workspaces\\APITesting\\Test.postman_collection.json" -e "C:\\workspaces\\APITesting\\Stage-
Test.postman_environment.json"


And also I used "Execute as Windows batch "
