### ISSUE TITLE
Unexpected identifier on any whitespace from imported csv data file

### ISSUE THREAD

**Issue by Sussumu** [postmanlabs/newman#1738]
1. Newman Version (can be found via `newman -v`): _4.1.0_

 2. OS details (type, version, and architecture): _Windows 10 Pro x64_

 3. Are you using Newman as a library, or via the CLI? _library (not working) and CLI (working fine)_

 3. Did you encounter this recently, or has this bug always been there: _found it now_

 4. Expected behaviour: _parse csv data and run the collection via library integration_

 5. Command / script used to run Newman: 

```
const newman = require('newman')
const collection = require('./collections/collection.json')
const environment = require('./environments/environment.json')
const data = require('./data/data.csv')

newman.run({
	collection: collection,
	environment: environment,
	iterationData: data
}, function (error) {
	if (error)
		throw error;
})
```

 6. Sample collection, and auxiliary files (minus the sensitive details):

```
id,name,email
1,name 1,example1@email.com
2,name 2,example2@email.com
3,name 3,example3@email.com
```

Steps to reproduce the problem:

1. Initialize a simple npm package with `npm init`
2. Add newman as a dependency
3. Add the code to index.js
4. Run `node index.js`
5. Receive the following error after any whitespace:

```
1;name 1;example1@email.com
       ^

SyntaxError: Unexpected number
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\gabri\Source\Repos\newman-recorder\index.js:4:14)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

**Comment by codenirvana** [comment]
@Sussumu CSV files can't be `require`d like this.

You have to specify the path to the CSV file to use `iterationData`, like:
```javascript
{..
    iterationData: './data/data.csv'
}
```

**Comment by Sussumu** [comment]
Nice, thanks!
