### ISSUE TITLE
Can not fetch global variable value in to the newman html report

### ISSUE THREAD

**Issue by musanas** [postmanlabs/newman#1794]
1. Newman Version (can be found via `newman -v`): 4.1.0 , newman-html-reporter : 1.0.2
 2. OS details (type, version, and architecture): Windows 10
 3. Are you using Newman as a library, or via the CLI? Tried both Library and CLI
 3. Did you encounter this recently, or has this bug always been there: Looks like its been there
 4. Expected behaviour: should be able to customize the HTML report with Global varibales in it

**What am trying to acheive here** : I wanted to generate a customized html report and this report should give information about the test env against which the collection was executed.

**What all I have done:** 
1. I have a collection json file and a global variables json file. There is a global variable callled **testEnv** in it.
2. I run the collection using Newman ( tried both CLI and library)
3. I wanted to generate a customized html file, hence i use a customized hbs file
4. I refered the below link
5. https://github.com/postmanlabs/newman/blob/develop/README.md#newmanruncallbackerror-object--summary-object
6. I understoood there is a **summary** object which returns most of the details that I want to show it in the report
7. I also underdtood there is **globals** object
8. I did console.log(JSON.stringify(summary.globals.values, null, 2)) using newman library
9. It showed me the list of globals values perfectly fine
10. I tried using the handlebars {{globals.values}} in the hbs 
11. Then I observed the below exception 
`RangeError: Maximum call stack size exceeded
    at PostmanVariableList.toString (C:\Development\CP-Bronze-Code-New\cloudpay-api-qa\node_modules\postman-collection\lib\collection\property-list.js:586:24)
    at PostmanVariableList.toString (C:\Development\CP-Bronze-Code-New\cloudpay-api-qa\node_modules\postman-collection\lib\collection\property-list.js:591:71)
    at PostmanVariableList.toString (C:\Development\CP-Bronze-Code-New\cloudpay-api-qa\node_modules\postman-collection\lib\collection\property-list.js:591:71)
    at PostmanVariableList.toString (C:\Development\CP-Bronze-Code-New\cloudpay-api-qa\node_modules\postman-collection\lib\collection\property-list.js:591:71)
    at PostmanVariableList.toString (C:\Development\CP-Bronze-Code-New\cloudpay-api-qa\node_modules\postman-collection\lib\collection\property-list.js:591:71)
    at PostmanVariableList.toString (C:\Development\CP-Bronze-Code-New\cloudpay-api-qa\node_modules\postman-collection\lib\collection\property-list.js:591:71)`

so looks like though the summary object has all the details in its hand, its not possible to get the global variable value to the html report

Thanks
Musaffir

**Comment by codenirvana** [comment]
@musanas You got this error because `globals` is an instance of [VariableList](https://www.postmanlabs.com/postman-collection/VariableList.html) and in handlebars `{{summary.globals.values}}` tries to get string value out of it i.e, `summary.globals.values.toString()`.

For your use case, to list all the global variables:
```hbs
{{#each summary.globals.values.members}}
    {{this.key}}: {{this.value}}
{{/each}}
```

or, to get the value of global variable named `testEnv`:
```hbs
{{summary.globals.values.reference.testEnv}}
```
