### ISSUE TITLE
Installation issue on CentOS 6.6: "Error: Could not locate the bindings file. Tried:"

### ISSUE THREAD

**Issue by arw180** [postmanlabs/newman#201]
I've installed newman on a CentOS 6.6 box and although the installation appears to succeed, trying to run newman results in the following:
```
/usr/lib/node_modules/newman/node_modules/jsdom/node_modules/contextify/node_modules/bindings/bindings.js:91
  throw err
        ^
Error: Could not locate the bindings file. Tried:
 → /usr/lib/node_modules/newman/node_modules/jsdom/node_modules/contextify/build/contextify.node
 → /usr/lib/node_modules/newman/node_modules/jsdom/node_modules/contextify/build/Debug/contextify.node
 → /usr/lib/node_modules/newman/node_modules/jsdom/node_modules/contextify/build/Release/contextify.node
 → /usr/lib/node_modules/newman/node_modules/jsdom/node_modules/contextify/out/Debug/contextify.node
 → /usr/lib/node_modules/newman/node_modules/jsdom/node_modules/contextify/Debug/contextify.node
 → /usr/lib/node_modules/newman/node_modules/jsdom/node_modules/contextify/out/Release/contextify.node
 → /usr/lib/node_modules/newman/node_modules/jsdom/node_modules/contextify/Release/contextify.node
 → /usr/lib/node_modules/newman/node_modules/jsdom/node_modules/contextify/build/default/contextify.node
 → /usr/lib/node_modules/newman/node_modules/jsdom/node_modules/contextify/compiled/0.10.33/linux/x64/contextify.node
    at bindings (/usr/lib/node_modules/newman/node_modules/jsdom/node_modules/contextify/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/usr/lib/node_modules/newman/node_modules/jsdom/node_modules/contextify/lib/contextify.js:1:96)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/newman/node_modules/jsdom/lib/jsdom/browser/index.js:5:21)
    at Module._compile (module.js:456:26)
```

I've Googled this to death and found a few claimed solutions, but nothing seems to work. It looks like the problem is ultimately with jsdom and it's dependency contextify. What's strange is that the file that it can't find (`contextify.node`), does actually exist at one of the paths it claims to be checking. I'll post this to the `jsdom` repo as well, but was curious if anyone here has seen this before

**Comment by abhijitkane** [comment]
What version of Node are you on? There's some issue Jsdom has with Node 0.12. Try 0.10 or 0.11 and see if that works. Alternatively, you can force install an older version (1.2.10) of Newman - `npm install newman@1.2.10`

**Comment by arw180** [comment]
I'm on Node v0.10.33, so I don't think that's the issue. Reverting to v1.2.10 of newman fixed the issue, so that works for me. Thanks!
