### ISSUE TITLE
ECONNRESET Socket hang up

### ISSUE THREAD

**Issue by ravish4596** [postmanlabs/newman#2142]
I am using request npm module, where i am calling a 3rd party API service. While calling request, i get error ECONNRESET:

Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1124:19)
    at TLSSocket.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:978:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
}

This issue is intermittent, not regular. I am not sure how to resolve this issue.

**Comment by codenirvana** [comment]
@ravish4596 are you getting this issue while using the https://github.com/request/request module or Newman?

**Comment by ravish4596** [comment]
@codenirvana We are using https://github.com/request/request module. We are not using Newman.

**Comment by codenirvana** [comment]
@ravish4596 Looks like you mistakenly opened this issue in Newman issue tracker instead.

I see similar issues are already opened in request [here](https://github.com/request/request/issues?utf8=✓&q=is%3Aissue+is%3Aopen+ECONNRESET).
Check if that fixes your issue else open a new issue in request issue tracker.
