### ISSUE TITLE
Newman error "stream.js:94, Error: EISDIR, read at Error (native)"

### ISSUE THREAD

**Issue by spiroskgr** [postmanlabs/newman#229]
I downloaded Newman in order to be able to download files using the collection runner. However, after trying to run a collection I always receive the following error:

Iteration 1 of 1
stream.js:94
throw er; // Unhandled stream error in pipe.
^
Error: EISDIR, read
at Error (native)
spyros@spyros-SZ77:~/npm-global/lib/node_modules/newman/bin$

Can you help me on how to proceed? 

You can have a look on the debug-log error here:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'show',
1 verbose cli   'newman',
1 verbose cli   'version' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 silly mapToRegistry name newman
5 silly mapToRegistry using default registry
6 silly mapToRegistry registry https://registry.npmjs.org/
7 silly mapToRegistry uri https://registry.npmjs.org/newman
8 verbose request uri https://registry.npmjs.org/newman
9 verbose request no auth needed
10 info attempt registry request try #1 at 15:52:01
11 verbose request id ce1a9baf4c8f840f
12 verbose etag "1F6L5R7NSLRPHX2OBX4Z3T1OK"
13 http request GET https://registry.npmjs.org/newman
14 http 304 https://registry.npmjs.org/newman
15 silly get cb [ 304,
15 silly get   { date: 'Wed, 15 Jul 2015 14:52:00 GMT',
15 silly get     via: '1.1 varnish',
15 silly get     'cache-control': 'max-age=60',
15 silly get     etag: '"1F6L5R7NSLRPHX2OBX4Z3T1OK"',
15 silly get     age: '0',
15 silly get     connection: 'keep-alive',
15 silly get     'x-served-by': 'cache-lhr6323-LHR',
15 silly get     'x-cache': 'HIT',
15 silly get     'x-cache-hits': '1',
15 silly get     'x-timer': 'S1436971920.156493,VS0,VE91',
15 silly get     vary: 'Accept' } ]
16 verbose etag https://registry.npmjs.org/newman from cache
17 verbose get saving newman to /home/spyros/.npm/registry.npmjs.org/newman/.cache.json
18 verbose exit [ 0, true ]
19 verbose stack Error: write EPIPE
19 verbose stack     at exports._errnoException (util.js:746:11)
19 verbose stack     at WriteWrap.afterWrite (net.js:775:14)
20 verbose cwd /home/spyros/npm-global/lib/node_modules/newman/bin
21 error Linux 3.13.0-57-generic
22 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "show" "newman" "version"
23 error node v0.12.7
24 error npm  v2.11.3
25 error code EPIPE
26 error errno EPIPE
27 error syscall write
28 error write EPIPE
29 error If you need help, you may report this error at:
29 error     <https://github.com/npm/npm/issues>
30 verbose exit [ 1, true ]

**Comment by StevenWatremez** [comment]
I have the same error when I run a collection. I don't know why. I thought it was an upload file cause my problem but Newman stop in a request which do not send file. And when I try to send this following request in Postman, it works very good.

**Comment by abhijitkane** [comment]
@StevenWatremez Can you attach a screenshot of your terminal window when you see the error?

**Comment by StevenWatremez** [comment]
![screen shot 2015-07-18 at 12 33 56](https://cloud.githubusercontent.com/assets/11426754/8761283/50c6676a-2d49-11e5-8b85-08161f94a781.png)

**Comment by abhijitkane** [comment]
Do you always see the error on the same request? Can you send your collection file to help@getpostman.com?

**Comment by StevenWatremez** [comment]
Yes I have the error on the same request. I sent to you my collection. I found something curious in my collection because in Postman I created 3 documents requests and I deleted one. But when I exported my collection as a JSON I found again my old document request in collection. But this following request not sent when I run with Newman.

**Comment by StevenWatremez** [comment]
I found this error. With Postman there are some request which are not visible, so when I export the collection I found more requests than in Postman. I am cleaning the collection. Normally it will work. Thanks for your help.

**Comment by a85** [comment]
All requests that exist in a collection should be visible in Postman too. Not sure why that would happen. @abhijitkane Thoughts?

**Comment by abhijitkane** [comment]
He deleted one request from the collection, so the behavior was as expected. The deleted request was still there in requests[], but not in order[]. I'll have to check how that happened - I'm not able to reproduce it now.

**Comment by artjulian** [comment]
Hi, I've run into the same problem and for me it turned out that this happened whenever I put my calls in separate subfolder within my collection. As soon as I took the calls out of my collection, the error went away.

**Comment by abhijitkane** [comment]
@artjulian Can you try duplicating the collection in Postman (with the calls in the subfolder), and trying with that?

**Comment by artjulian** [comment]
@abhijitkane I've tried, but was unable to reproduce the issue. Weird, cause getting them out of the folder did generate a collection.json that didn't have the problem anymore. I've also lost the previous faulty collection, so I'm not able to do a compare. 

Will log it better next time I run into it.

**Comment by artjulian** [comment]
@abhijitkane I ran into this issue again today and was able to successfully isolate the problem. It was a single request that was causing the error. This is the only request in the list that uses file-uploading.

This is a "form-data" request with a file as a parameter. When this request is removed from the collection, the error disappears.

**Comment by abhijitkane** [comment]
Is the file available at the location you're running Newman from? Try using the complete path of the file in place of the file name (in the collection JSON).
http://blog.getpostman.com/2014/11/15/using-newman-to-run-collections-with-file-post-requests/

**Comment by davenewza** [comment]
I have the same problem. It occurs on a request which is attempting to post a file.

Here is that section in json:

```json
  {
	  "id": "dd27b72a-6ce3-0dee-2e39-765396614422",
	  "headers": "Content-Type: application/json\n",
	  "url": "{{SchedulingUrl}}/schedules/{{ScheduleId}}",
	  "preRequestScript": "",
	  "pathVariables": {},
	  "method": "GET",
	  "data": [
		  {
			  "key": "jsonFile", 
			  "value": "C:/a/8ac4a4f6/Root/test/Postman/IntegrationSeed.json",
			  "type": "file",
			  "enabled": true
		  }
	  ],
	  "dataMode": "params",
	  "version": 2,
	  "tests": "...removed...",
	  "currentHelper": "normal",
	  "helperAttributes": {},
	  "time": 1442484800396,
	  "name": "Schedule",
	  "description": "",
	  "collectionId": "1e888875-18ac-a772-4d63-809bb9f45b59",
	  "responses": []
  }
```

**Comment by abhijitkane** [comment]
@davenewza Can you change the file to `"value": "IntegrationSeed.json",`, and try running newman -c <filename> from `C:/a/2a34a4f6/Root/test/Postman`?

**Comment by kunagpal** [comment]
@davenewza Please see #570 for more details, sincerest apologies for the delay.
Closing issue due to inactivity.
