### ISSUE TITLE
Newman- Escaping Backslashes in Environment Variable

### ISSUE THREAD

**Issue by wirsingj** [postmanlabs/newman#244]
Hey,

I have a collection that runs fine in postman- but in newman crashes upon reading in an environment variable. The variable is a Completed Session ID, can contain back slashes, and is dynamically generated by the server each run.

 It should be noted that this issue doesn't happen the FIRST time I run a collection (with new name) after downloading the collection from postman- only the runs after the first crash:

\K3.... kills it.

y":"CompletedSession","value":"SVpSZhWQEqhESLYRFXQBsk./RX/dNG4f8qHQ\K3om1duzLO

SyntaxError: Unexpected token K
at Object.parse (native)
at Object. (/usr/local/lib/node_modules/newman/src/utilities/VariableProcessor.js:113:32)
at /usr/local/lib/node_modules/newman/node_modules/underscore/underscore.js:73:21
at Function..each..forEach (/usr/local/lib/node_modules/newman/node_modules/underscore/underscore.js:153:9)
at Object.jsface.Class._processEnvVariable (/usr/local/lib/node_modules/newman/src/utilities/VariableProcessor.js:103:8)
at Object.jsface.Class.processRequestVariables (/usr/local/lib/node_modules/newman/src/utilities/VariableProcessor.js:132:8)
at Object.jsface.Class._processUrlUsingEnvVariables (/usr/local/lib/node_modules/newman/src/runners/RequestRunner.js:295:21)
at Object.jsface.Class._execute (/usr/local/lib/node_modules/newman/src/runners/RequestRunner.js:161:9)
at null._onTimeout (/usr/local/lib/node_modules/newman/src/runners/RequestRunner.js:222:11)
at Timer.listOnTimeout (timers.js:119:15)

**Comment by wirsingj** [comment]
I also find it odd that its throwing this error AFTER it has used this session token in a variable in a header, and received the response:

200 600ms Cart https://*************v1/api/cart
    ✔ Status code is 200
    ✔ Has Item
    ✔ Correct ProductId

undefined:1
QfciUXFH7OrD-k4z3-UC3a.pYxHHhzC8_n88s9ShNI1Moux7KYdJYPzrvPjoesqrSUm\gGNM4ns4DK
                                                                    ^
SyntaxError: Unexpected token g
    at Object.parse (native)
    at Object.<anonymous> (/usr/local/lib/node_modules/newman/src/utilities/VariableProcessor.js:113:32)

**Comment by abhijitkane** [comment]
@wirsingj I'm not able to reproduce this - can you send a sample collection/env file that reproduces this to help@getpostman.com?
