### ISSUE TITLE
Connection pool for asynchronous runs/collections

### ISSUE THREAD

**Issue by der-kommissar** [postmanlabs/newman#2561]
**Enhancement idea:** Provide a connection pool or some other mechanism to reuse HTTP connections across parallel runs. 
This could be an optional connectionPool type param that passes a reference to a connectionPool back and forth and is tied to a queue maintained internally and reuses some configured set of connections to make requests.

**Note:** This is not the same as this postman-runtime issue: [Add concurrency (parallel runs) support](https://github.com/postmanlabs/postman-runtime/pull/867). That issue is asking for the ability to have concurrent runs of the _same_ collection, rather than concurrent runs of _separate_ collections.

**Background:** I am using the newman library to run multiple collections asynchronously, using Javascript promises. These collections can be run independently from one another and most of them will run in multiple environments. I'm hitting a connection limit as our suite of collections have grown resulting in errors like this:  
>Error: read ECONNRESET  
>    at _errnoException (util.js:1024:11)  
>    at TLSWrap.onread (net.js:615:25)  

My immediate solution is to create a run queue to limit the number of parallel runs (and thus number of connections), but it would be great to have something that worked more out-of-the-box. Ideally, newman would accept a batch of collections and handle all the aspects of queuing/pooling internally.

 1. Newman Version (can be found via `newman -v`): 4.5.1
 2. OS details (type, version, and architecture): Windows
 3. Are you using Newman as a library, or via the CLI? Library
 3. Did you encounter this recently, or has this bug always been there: Always

**Comment by shamasis** [comment]
Does postman-request have connection pool configurations? We can then make that configurable via options.

The most appropriate place to have the pool is in postman-request. And it already has one in form of Node's original pool (just a guess.)

**Comment by johnmusk** [comment]
is this issue is still open

**Comment by adityaofficial10** [comment]
@johnmusk 
I'm working with it already.
