### ISSUE TITLE
Fail to install newman via npm@2.14.0

### ISSUE THREAD

**Issue by laiyuncong8404** [postmanlabs/newman#277]
I have this problem when install newman.

here is the log
```shell

C:\Users\Administrator\AppData\Roaming\npm>npm install -g newman --registry=https://registry.npm.taobao.org
|


> contextify@0.1.14 install C:\Users\Administrator\AppData\Roaming\npm\node_modules\newman\node_modules\jsdom\node_modules\contextify
> node-gyp rebuild

\
C:\Users\Administrator\AppData\Roaming\npm\node_modules\newman\node_modules\jsdom\node_modules\contextify>if not defined npm_config_node_gyp (node "C:\Users\Adm
inistrator\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at exports._errnoException (util.js:746:11)
gyp ERR! stack     at TCP.onread (net.js:559:26)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Administrator\AppData\Roaming\npm\node_modules\newman\node_modules\jsdom\node_modules\contextify
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "node" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "newman" "--registry=https://registry.
npm.taobao.org"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.0
npm ERR! code ELIFECYCLE

npm ERR! contextify@0.1.14 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the contextify@0.1.14 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm\npm-debug.log

C:\Users\Administrator\AppData\Roaming\npm>npm install -g newman@1.2.13 --registry=https://registry.npm.taobao.org
-


> contextify@0.1.14 install C:\Users\Administrator\AppData\Roaming\npm\node_modules\newman\node_modules\jsdom\node_modules\contextify
> node-gyp rebuild

/
C:\Users\Administrator\AppData\Roaming\npm\node_modules\newman\node_modules\jsdom\node_modules\contextify>if not defined npm_config_node_gyp (node "C:\Users\Adm
inistrator\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at exports._errnoException (util.js:746:11)
gyp ERR! stack     at TCP.onread (net.js:559:26)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Administrator\AppData\Roaming\npm\node_modules\newman\node_modules\jsdom\node_modules\contextify
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "node" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "newman@1.2.13" "--registry=https://re
gistry.npm.taobao.org"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.0
npm ERR! code ELIFECYCLE

npm ERR! contextify@0.1.14 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the contextify@0.1.14 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm\npm-debug.log

C:\Users\Administrator\AppData\Roaming\npm>
```

**Comment by czardoz** [comment]
The installer was downloading something, and the connection got reset.. 
```
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at exports._errnoException (util.js:746:11)
gyp ERR! stack     at TCP.onread (net.js:559:26)
```

**Comment by czardoz** [comment]
@laiyuncong8404 is this a recurrent problem? What happens if you retry installation?

**Comment by laiyuncong8404** [comment]
@czardoz 
I have upgrade VS from 2010 to 2015,
and I retry using the official registry,but still fail :(
This time I got a gyp error notice

```shell
c:\>npm install -g newman --registry=https://registry.npmjs.org
\
> contextify@0.1.14 install C:\Users\Administrator\AppData\Roaming\npm\node_modules\newman\node_modules\jsdom\node_modules\contextify
> node-gyp rebuild
\
C:\Users\Administrator\AppData\Roaming\npm\node_modules\newman\node_modules\jsdom\node_modules\contextify>if not defined npm_config_node_gyp (node "C:\Users\Adm
inistrator\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp: C:\Users\Administrator\.node-gyp\0.12.7\common.gypi not found (cwd: C:\Users\Administrator\AppData\Roaming\npm\node_modules\newman\node_modules\jsdom\node_
modules\contextify) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:357:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Administrator\AppData\Roaming\npm\node_modules\newman\node_modules\jsdom\node_modules\contextify
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "node" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "newman" "--registry=https://registry.
npmjs.org"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.0
npm ERR! code ELIFECYCLE

npm ERR! contextify@0.1.14 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the contextify@0.1.14 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\npm-debug.log
```

**Comment by czardoz** [comment]
I think that is because your during your previous try, newman was only partly downloaded in your ``node_modules`` folder. Can you delete ``C:\Users\Administrator\AppData\Roaming\npm\node_modules\newman`` before trying again?

We also have released a beta version that does not require Visual Studio, but you will need node 4.0+ for it to work. You can install it by running

```
npm install -g newman@beta
```

**Comment by laiyuncong8404** [comment]
There is no 'newman' folder before I run the install command
under ``` C:\Users\Administrator\AppData\Roaming\npm\node_modules``` or ```  C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules```
Maybe I should take your advice to try 
```npm install -g newman@beta```

But this will need node 4.0+ as you mentioned, I had install 'Appium' which need node 0.12+, I don't know whether the node will conflict or not.

Thanks for your help after all.

**Comment by czardoz** [comment]
@laiyuncong8404 Well, ultimately, the issue is incomplete download of the required installation files. 

As a last resort, you can try using https://github.com/arei/npmbox to package everything into one file, and then install using that file, to make sure everything is being downloaded properly.

**Comment by laiyuncong8404** [comment]
@czardoz  Good news.
I had downgrade node from v0.12.7.0 to v0.10.26.0, then 'contextify' can be installed, so does 'newman'.
Thanks again for your help.
