### ISSUE TITLE
Deprecated dependencies

### ISSUE THREAD

**Issue by sl4ng3r** [postmanlabs/newman#2924]
1.Newman Version 5.3.1
2. Linux / Mac
3. Using Newman as CLI
4. Always

Hi, 
if i install newman with npm, i always get some deprecated messages. 

npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

At the moment, it is no problem, but soon I think it will be blocked by our security policies. 

Is it possible to upgrade these dependencies?

Frendly regards. 

Alex

**Comment by Tusharkhati** [comment]
can I work on this?
Thanks.

**Comment by jasvday12** [comment]
I am experiencing the same issue. I tried to install newer version har-validator for example: @plotdb/har-validator@5.1.6 but it newman does not take it and still install old har-validator@5.1.5. 

I run: 
#npm install -g newman newman-reporter-htmlextra@1.22.8 @plotdb/har-validator@5.1.6
#npm install -g yarn@1.22.10

And after installation i get: 
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated gulp-header@1.8.12: Removed event-stream from gulp-header
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated

Does anyone know if those dependencies can be upgraded ?

**Comment by federicomanco** [comment]
Experiencing the same behavior.

**Comment by JeffJacobson** [comment]
> I am experiencing the same issue. I tried to install newer version har-validator for example: @plotdb/har-validator@5.1.6 but it newman does not take it and still install old har-validator@5.1.5.
> 
> I run: #npm install -g newman newman-reporter-htmlextra@1.22.8 @plotdb/har-validator@5.1.6 #npm install -g yarn@1.22.10
> 
> And after installation i get: npm WARN ...
> 
> Does anyone know if those dependencies can be upgraded?

You can override the "uuid" package to a later version, but overriding "har-validator" with "@plotdb/har-validator" will cause problems when running newman.

You can [override dependencies in your `package.json` file](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides)...

```json
  "devDependencies": {
    "newman": "^5.3.2"
  },
  "overrides": {
    "uuid": "^7.0.0",
    "har-validator": "@plotdb/har-validator"
  }
```

However, overriding "har-validator" with "@plotdb/har-validator" will generate errors when running `newman run`, as shown below. (You can still override "uuid" as shown above, though.)

```log
node:internal/modules/cjs/loader:959
  throw err;
  ^

Error: Cannot find module 'har-validator'
Require stack:
- C:\Users\YourName\source\repos\postman-configs\node_modules\postman-request\lib\har.js      
- C:\Users\YourName\source\repos\postman-configs\node_modules\postman-request\request.js      
- C:\Users\YourName\source\repos\postman-configs\node_modules\postman-request\index.js        
- C:\Users\YourName\source\repos\postman-configs\node_modules\postman-runtime\lib\requester\request-wrapper.js
- C:\Users\YourName\source\repos\postman-configs\node_modules\postman-runtime\lib\requester\requester.js
- C:\Users\YourName\source\repos\postman-configs\node_modules\postman-runtime\lib\requester\index.js
- C:\Users\YourName\source\repos\postman-configs\node_modules\postman-runtime\lib\runner\extensions\http-request.command.js
- C:\Users\YourName\source\repos\postman-configs\node_modules\postman-runtime\lib\runner\run.js
- C:\Users\YourName\source\repos\postman-configs\node_modules\postman-runtime\lib\runner\index.js
- C:\Users\YourName\source\repos\postman-configs\node_modules\postman-runtime\lib\index.js    
- C:\Users\YourName\source\repos\postman-configs\node_modules\postman-runtime\index.js        
- C:\Users\YourName\source\repos\postman-configs\node_modules\newman\lib\run\index.js
- C:\Users\YourName\source\repos\postman-configs\node_modules\newman\lib\index.js
- C:\Users\YourName\source\repos\postman-configs\node_modules\newman\index.js
- C:\Users\YourName\source\repos\postman-configs\node_modules\newman\bin\newman.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Module._load (node:internal/modules/cjs/loader:804:27)
    at Module.require (node:internal/modules/cjs/loader:1022:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\YourName\source\repos\postman-configs\node_modules\postman-request\lib\har.js:5:16)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1022:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\YourName\source\repos\postman-configs\node_modules\postman-request\request.js:26:11)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Module._load (node:internal/modules/cjs/loader:839:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\YourName\\source\\repos\\postman-configs\\node_modules\\postman-request\\lib\\har.js',
    'C:\\Users\\YourName\\source\\repos\\postman-configs\\node_modules\\postman-request\\request.js',
    'C:\\Users\\YourName\\source\\repos\\postman-configs\\node_modules\\postman-request\\index.js',
    'C:\\Users\\YourName\\source\\repos\\postman-configs\\node_modules\\postman-runtime\\lib\\requester\\request-wrapper.js',
    'C:\\Users\\YourName\\source\\repos\\postman-configs\\node_modules\\postman-runtime\\lib\\requester\\requester.js',
    'C:\\Users\\YourName\\source\\repos\\postman-configs\\node_modules\\postman-runtime\\lib\\requester\\index.js',
    'C:\\Users\\YourName\\source\\repos\\postman-configs\\node_modules\\postman-runtime\\lib\\runner\\extensions\\http-request.command.js',
    'C:\\Users\\YourName\\source\\repos\\postman-configs\\node_modules\\postman-runtime\\lib\\runner\\run.js',
    'C:\\Users\\YourName\\source\\repos\\postman-configs\\node_modules\\postman-runtime\\lib\\runner\\index.js',
    'C:\\Users\\YourName\\source\\repos\\postman-configs\\node_modules\\postman-runtime\\lib\\index.js',
    'C:\\Users\\YourName\\source\\repos\\postman-configs\\node_modules\\postman-runtime\\index.js',
    'C:\\Users\\YourName\\source\\repos\\postman-configs\\node_modules\\newman\\lib\\run\\index.js',
    'C:\\Users\\YourName\\source\\repos\\postman-configs\\node_modules\\newman\\lib\\index.js',
    'C:\\Users\\YourName\\source\\repos\\postman-configs\\node_modules\\newman\\index.js',    
    'C:\\Users\\YourName\\source\\repos\\postman-configs\\node_modules\\newman\\bin\\newman.js'
  ]
}
```

**Comment by dkoz1** [comment]
@JeffJacobson  thank you for your response, are you maybe aware of any workaround which would not generate errors ?

**Comment by JeffJacobson** [comment]
> @JeffJacobson thank you for your response, are you maybe aware of any workaround which would not generate errors ?

Sorry, I don't know of any workaround.

Also, when running `newman run` with the aforementioned "override" to the latest version of `uuid`, I get this warning:

```node
(node:12380) DeprecationWarning: Deep requiring like `const uuidv4 = require('uuid/v4');` is deprecated as of uuid@7.x. Please require the top-level module when using the Node.js CommonJS module or use ECMAScript Modules when bundling for the browser. See https://github.com/uuidjs/uuid#deep-requires-now-deprecated for more information.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

Looks like there's no way to avoid warnings until newman is updated to resolve these issues. ☹

**Comment by JeffJacobson** [comment]
It looks like the issues may be coming from the ["postman-request"](https://github.com/postmanlabs/postman-request) dependency rather than directly from this repo.

* There's already a [pull request there to upgrade its uuid dependency to a newer version](https://github.com/postmanlabs/postman-request/pull/85).

**Comment by jasvday12** [comment]
@JeffJacobson thank you for your insights :) It looks like we have to just wait until PR is completed.

**Comment by silverwind** [comment]
These are coming from third-party dependencies `serialised-error` and `postman-request`:


```
newman@6.0.0
┬ serialised-error@1.1.3
└── uuid@3.4.0
┬ postman-request@2.88.1-postman.33
└── har-validator@5.1.5
```

**Comment by davidcao1337** [comment]
Are there any plans on replacing har-validator with something else in postman-requests?
