### ISSUE TITLE
java.io.IOException: error=2, No such file or directory while running with newman in jenkins for postman collection

### ISSUE THREAD

**Issue by deepika57** [postmanlabs/newman#2925]
In Console Output : I am facing this issue , can some one help me how to resolve this .

Started by user [amrutha](http://localhost:8080/user/amrutha)
Running as SYSTEM
Building in workspace /var/jenkins_home/workspace/PostmanUnitTests
[PostmanUnitTests] $ cmd /c call /tmp/jenkins14743462721181469992.bat
FATAL: command execution failed
java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(Unknown Source)
	at java.base/java.lang.ProcessImpl.start(Unknown Source)
Caused: java.io.IOException: Cannot run program "cmd" (in directory "/var/jenkins_home/workspace/PostmanUnitTests"): error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at hudson.Proc$LocalProc.<init>(Proc.java:252)
	at hudson.Proc$LocalProc.<init>(Proc.java:221)
	at hudson.Launcher$LocalLauncher.launch(Launcher.java:995)
	at hudson.Launcher$ProcStarter.start(Launcher.java:507)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:143)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:91)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:806)
	at hudson.model.Build$BuildExecution.build(Build.java:198)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:514)
	at hudson.model.Run.execute(Run.java:1888)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:99)
	at hudson.model.Executor.run(Executor.java:432)
Build step 'Execute Windows batch command' marked build as failure
Finished: FAILURE

**Comment by deepika57** [comment]
In build I have given this 
C:\Users\hp\AppData\Roaming\npm\newman -c "C:\Users\hp\Desktop\postman\DoctorApp.postman_collection.json" -e
"C:\Users\hp\Desktop\postman\DoctorApp.postman_environment.json"
