### ISSUE TITLE
Cannot use newman with prerequest script

### ISSUE THREAD

**Issue by cyrildubus** [postmanlabs/newman#293]
Hi, 

I cannot use newman (just installed) with a pre-request script.

I expect that line to work 

newman -u https://www.getpostman.com/collections/ec0c4e50adcd87aabdf4
(very simple use case)

And it's failing with this error :
 
TypeError: 'caller' and 'arguments' are restricted function properties and cannot be accessed in this context.
    at Array.<anonymous> (/usr/local/lib/node_modules/newman/src/utilities/PreRequestScriptProcessor.js:147:110)
    at arrayEach (/usr/local/lib/node_modules/newman/node_modules/sugar/release/sugar-full.development.js:934:20)
    at Array.extend.each (/usr/local/lib/node_modules/newman/node_modules/sugar/release/sugar-full.development.js:1815:7)
    at Object.jsface.Class._createSandboxedEnvironment (/usr/local/lib/node_modules/newman/src/utilities/PreRequestScriptProcessor.js:147:56)
    at Object.jsface.Class.runPreRequestScript (/usr/local/lib/node_modules/newman/src/utilities/PreRequestScriptProcessor.js:42:32)
    at Object.jsface.Class._execute (/usr/local/lib/node_modules/newman/src/runners/RequestRunner.js:162:15)
    at null._onTimeout (/usr/local/lib/node_modules/newman/src/runners/RequestRunner.js:86:20)
    at Timer.listOnTimeout (timers.js:92:15)

If I remove the pre-request script, it's working.

Am I doing something wrong or is it a bug ?

**Comment by czardoz** [comment]
You're using Node v4+, so you'll have to install Newman Beta.

You can install it by running:

```npm install -g newman@beta ```

The readme has this information, but I think it's not very clear right now, I'll keep this issue open until I update it :-)

**Comment by czardoz** [comment]
Fixed with 087fc8579883ef428f1e565a951a3388b778d5ca

**Comment by cyrildubus** [comment]
Thank you, it is indeed working.

But I did not manage to install newman beta with -g option, due to the jsdom permission bug (already deposed on this issue tracker). I did manage to install it locally for a user but not with -g

**Comment by czardoz** [comment]
Works fine for me in Ubuntu. Will investigate the issue on a Mac.

**Comment by cyrildubus** [comment]
I'm working on debian 8, with nodejs 4.2.2 
One of my collaborator had the same problem (jsdom permission bug) today with debian 7 and nodejs 4.2.2

I think somewhere in the deployement script the user is changed and this user does not have the right permissions set.

Anyway it's working fine without the "-g" option so it's not a major problem, we can still use it.

**Comment by czardoz** [comment]
Ah I see. I guess this is the issue that you're referring to: https://github.com/postmanlabs/newman/issues/288

I'll try to reproduce it today. Also, if you have it, a stack trace would help out a lot :)

**Comment by cyrildubus** [comment]
yes I will put the trace on this issue instead of here

**Comment by czardoz** [comment]
fixed with cc0dd557eb9bc387cfa1fe84bc36ed00363f98d5
