### ISSUE TITLE
TestResponseHandler: 'caller' and 'arguments' are restricted function properties

### ISSUE THREAD

**Issue by matteogit** [postmanlabs/newman#294]
Hi all,
when i try to add some test to a request, running from postman extension works fine, but when running from newman, i get the following error

```javascript
user@ubuntubox:~/work/service-api-tests$ newman -x -c /home/user/work/service-api-tests/tests/test.json.postman_collection -e /home/user/work/service-api-tests/environments/seed-production.postman_environment 

Iteration 1 of 1
/usr/lib/node_modules/newman/src/responseHandlers/TestResponseHandler.js:172
        Object.getOwnPropertyNames(Function.prototype).each(function(p) { sugar.funcs[p] = Function.prototype[p];});
                                                                                                             ^

TypeError: 'caller' and 'arguments' are restricted function properties and cannot be accessed in this context.
    at Array.<anonymous> (/usr/lib/node_modules/newman/src/responseHandlers/TestResponseHandler.js:172:110)
    at arrayEach (/usr/lib/node_modules/newman/node_modules/sugar/release/sugar-full.development.js:934:20)
    at Array.extend.each (/usr/lib/node_modules/newman/node_modules/sugar/release/sugar-full.development.js:1815:7)
    at Object.jsface.Class._createSandboxedEnvironment (/usr/lib/node_modules/newman/src/responseHandlers/TestResponseHandler.js:172:56)
    at Object.jsface.Class._runTestCases (/usr/lib/node_modules/newman/src/responseHandlers/TestResponseHandler.js:50:32)
    at Object.jsface.Class._onRequestExecuted (/usr/lib/node_modules/newman/src/responseHandlers/TestResponseHandler.js:37:28)
    at emitMany (events.js:113:20)
    at EventEmitter.emit (events.js:182:7)
    at Object.jsface.Class.emit (/usr/lib/node_modules/newman/src/utilities/EventEmitter.js:34:16)
    at Object.<anonymous> (/usr/lib/node_modules/newman/src/runners/RequestRunner.js:199:10)
```

i tried different code in the "test" prop, but even if i only declare a simple var, i get this error. if i leave the "test" property empty, all goes well

node 4.2.2
npm 2.4.17
newman from latest - 1.2.16

**Comment by czardoz** [comment]
Hi @matteogit, you need to install Newman Beta, as detailed here: https://github.com/postmanlabs/newman/#supported-node-versions

**Comment by tedmiston** [comment]
@czardoz +1 I had the same issue.

Perhaps it might be worthwhile to print out an error message in this case when running the non-beta version.
