### ISSUE TITLE
TypeError: Cannot read property '_visited' of null

### ISSUE THREAD

**Issue by markbucknellcc** [postmanlabs/newman#296]
Every time I run execute newman I get the following error:

```
vagrant@vagrant-ubuntu-trusty-64:/vagrant/api/postman$ newman -c 123360dmg.com.json.postman_collection -
e clients.postman_environment

Iteration 1 of 1
200 435ms JWT: Login [GET] http://local.zak.api.360dmg.com/jwt/login
    ? Status code is 200
    ? Login matches auth user
    ? Token expiry is in future
    ? JWT prn role is staff
/usr/lib/node_modules/newman/src/utilities/VariableProcessor.js:144
                if(o._visited) {
                    ^
TypeError: Cannot read property '_visited' of null
    at Object.jsface.Class._traverseJson (/usr/lib/node_modules/newman/src/utilities/VariableProcessor.j
s:144:7)
    at Object.<anonymous> (/usr/lib/node_modules/newman/src/utilities/VariableProcessor.js:123:14)
    at /usr/lib/node_modules/newman/node_modules/underscore/underscore.js:73:21
    at Function._.each._.forEach (/usr/lib/node_modules/newman/node_modules/underscore/underscore.js:153
:9)
    at Object.jsface.Class._processEnvVariable (/usr/lib/node_modules/newman/src/utilities/VariableProce
ssor.js:114:8)
    at Object.jsface.Class.processRequestVariables (/usr/lib/node_modules/newman/src/utilities/VariableP
rocessor.js:173:8)
    at Object.jsface.Class._processUrlUsingEnvVariables (/usr/lib/node_modules/newman/src/runners/Reques
tRunner.js:301:27)
    at Object.jsface.Class._execute (/usr/lib/node_modules/newman/src/runners/RequestRunner.js:161:9)
    at null._onTimeout (/usr/lib/node_modules/newman/src/runners/RequestRunner.js:222:11)
    at Timer.listOnTimeout (timers.js:119:15)'
```

I would appreciate anyone's help!

**Comment by czardoz** [comment]
@markbucknellcc what newman version are you on?

**Comment by markbucknellcc** [comment]
Newman - 1.2.23

**Comment by markbucknellcc** [comment]
I managed to fix this problem by creating a new collection file and copying all the requests over. There must be some sort of corruption, potentially an id that doesn't match up or something. It just doesn't make much sense since it works perfectly fine in Postman.
