### ISSUE TITLE
Newman error: TypeError: 'caller' and 'arguments' are restricted function properties and cannot be accessed in this context.

### ISSUE THREAD

**Issue by szantner** [postmanlabs/newman#300]
When using node 4.2.1 newman returns:

TypeError: 'caller' and 'arguments' are restricted function properties and cannot be accessed in this context.
    at Array.<anonymous> (/Users/noname/.nvm/versions/node/v4.2.1/lib/node_modules/newman/src/utilities/PreRequestScriptProcessor.js:152:48)
    at arrayEach (/Users/noname/.nvm/versions/node/v4.2.1/lib/node_modules/newman/node_modules/sugar/release/sugar-full.development.js:934:20)
    at Array.extend.each (/Users/noname/.nvm/versions/node/v4.2.1/lib/node_modules/newman/node_modules/sugar/release/sugar-full.development.js:1815:7)
    at Object.jsface.Class._createSandboxedEnvironment (/Users/noname/.nvm/versions/node/v4.2.1/lib/node_modules/newman/src/utilities/PreRequestScriptProcessor.js:151:56)
    at Object.jsface.Class.runPreRequestScript (/Users/noname/.nvm/versions/node/v4.2.1/lib/node_modules/newman/src/utilities/PreRequestScriptProcessor.js:42:32)
    at Object.jsface.Class._execute (/Users/noname/.nvm/versions/node/v4.2.1/lib/node_modules/newman/src/runners/RequestRunner.js:162:24)
    at null._onTimeout (/Users/noname/.nvm/versions/node/v4.2.1/lib/node_modules/newman/src/runners/RequestRunner.js:86:20)
    at Timer.listOnTimeout (timers.js:92:15)
[12:59:01] 'newman:local:general' errored after 1.25 s
[12:59:01] Error: Command `newman -c ./migrations/newman/setup-general.json -e ./migrations/newman/_env/localhost-v1.json -n 1 -y 0` failed with exit code 1
    at ChildProcess.exithandler (child_process.js:203:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)

**Comment by czardoz** [comment]
Hi, this is because Node v4+ is only supported by Newman Beta at the moment.  Check the readme for details: https://github.com/postmanlabs/newman
