### ISSUE TITLE
Not able to install newman

### ISSUE THREAD

**Issue by zonito** [postmanlabs/newman#303]
```
[20:10:08][Step 1/2] ../node_modules/nan/nan.h:328: error: ‘REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’
[20:10:08][Step 1/2] make: *** [Release/obj.target/contextify/src/contextify.o] Error 1
[20:10:08][Step 1/2] make: Leaving directory `/mnt/data/buildAgent/work/57d2ff7c9840fab3/newman/lib/node_modules/newman/node_modules/jsdom/node_modules/contextify/build'
[20:10:08][Step 1/2] gyp ERR! build error 
[20:10:08][Step 1/2] gyp ERR! stack Error: `make` failed with exit code: 2
[20:10:08][Step 1/2] gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:267:23)
[20:10:08][Step 1/2] gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
[20:10:08][Step 1/2] gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
[20:10:08][Step 1/2] gyp ERR! System Linux 2.6.32-504.12.2.el6.x86_64
[20:10:08][Step 1/2] gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
[20:10:08][Step 1/2] gyp ERR! cwd /mnt/data/buildAgent/work/57d2ff7c9840fab3/newman/lib/node_modules/newman/node_modules/jsdom/node_modules/contextify
[20:10:08][Step 1/2] gyp ERR! node -v v0.10.36
[20:10:08][Step 1/2] gyp ERR! node-gyp -v v0.10.6
[20:10:08][Step 1/2] gyp ERR! not ok 
[20:10:08][Step 1/2] npm ERR! Error: ENOENT, chmod '/mnt/data/buildAgent/work/57d2ff7c9840fab3/newman/lib/node_modules/newman/node_modules/jsdom/node_modules/cssstyle/lib/properties/webkitTextFillColor.js'
[20:10:08][Step 1/2] npm ERR! If you need help, you may report this log at:
[20:10:08][Step 1/2] npm ERR!     <http://github.com/isaacs/npm/issues>
[20:10:08][Step 1/2] npm ERR! or email it to:
[20:10:08][Step 1/2] npm ERR!     <npm-@googlegroups.com>
[20:10:08][Step 1/2] 
[20:10:08][Step 1/2] npm ERR! System Linux 2.6.32-504.12.2.el6.x86_64
[20:10:08][Step 1/2] npm ERR! command "node" "/usr/bin/npm" "install" "-g" "newman" "--prefix" "newman/"
[20:10:08][Step 1/2] npm ERR! cwd /mnt/data/buildAgent/work/57d2ff7c9840fab3
[20:10:08][Step 1/2] npm ERR! node -v v0.10.36
[20:10:08][Step 1/2] npm ERR! npm -v 1.3.6
[20:10:08][Step 1/2] npm ERR! path /mnt/data/buildAgent/work/57d2ff7c9840fab3/newman/lib/node_modules/newman/node_modules/jsdom/node_modules/cssstyle/lib/properties/webkitTextFillColor.js
[20:10:08][Step 1/2] npm ERR! fstream_path /mnt/data/buildAgent/work/57d2ff7c9840fab3/newman/lib/node_modules/newman/node_modules/jsdom/node_modules/cssstyle/lib/properties/webkitTextFillColor.js
[20:10:08][Step 1/2] npm ERR! fstream_type File
[20:10:08][Step 1/2] npm ERR! fstream_class FileWriter
[20:10:08][Step 1/2] npm ERR! fstream_finish_call chmod
[20:10:08][Step 1/2] npm ERR! code ENOENT
[20:10:08][Step 1/2] npm ERR! errno 34
[20:10:08][Step 1/2] npm ERR! fstream_stack /usr/lib/node_modules/fstream/lib/writer.js:305:19
[20:10:08][Step 1/2] npm ERR! fstream_stack Object.oncomplete (fs.js:108:15)
[20:10:08][Step 1/2] npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/mnt/data/buildAgent/work/57d2ff7c9840fab3/newman/lib/node_modules/newman/node_modules/lodash'
[20:10:08][Step 1/2] npm ERR! error rolling back  newman@1.2.25 { [Error: ENOTEMPTY, rmdir '/mnt/data/buildAgent/work/57d2ff7c9840fab3/newman/lib/node_modules/newman/node_modules/lodash']
[20:10:08][Step 1/2] npm ERR! error rolling back   errno: 53,
[20:10:08][Step 1/2] npm ERR! error rolling back   code: 'ENOTEMPTY',
[20:10:08][Step 1/2] npm ERR! error rolling back   path: '/mnt/data/buildAgent/work/57d2ff7c9840fab3/newman/lib/node_modules/newman/node_modules/lodash' }
[20:10:08][Step 1/2] npm ERR! weird error 1
[20:10:08][Step 1/2] npm ERR! Error: ENOENT, lstat '/mnt/data/buildAgent/work/57d2ff7c9840fab3/newman/lib/node_modules/newman/node_modules/unirest/docs/unirest/0.3.8/module-marshals_cookies.html'
[20:10:08][Step 1/2] npm ERR! If you need help, you may report this log at:
[20:10:08][Step 1/2] npm ERR!     <http://github.com/isaacs/npm/issues>
[20:10:08][Step 1/2] npm ERR! or email it to:
[20:10:08][Step 1/2] npm ERR!     <npm-@googlegroups.com>
[20:10:08][Step 1/2] 
[20:10:08][Step 1/2] npm ERR! System Linux 2.6.32-504.12.2.el6.x86_64
[20:10:08][Step 1/2] npm ERR! command "node" "/usr/bin/npm" "install" "-g" "newman" "--prefix" "newman/"
[20:10:08][Step 1/2] npm ERR! cwd /mnt/data/buildAgent/work/57d2ff7c9840fab3
[20:10:08][Step 1/2] npm ERR! node -v v0.10.36
[20:10:08][Step 1/2] npm ERR! npm -v 1.3.6
[20:10:08][Step 1/2] npm ERR! path /mnt/data/buildAgent/work/57d2ff7c9840fab3/newman/lib/node_modules/newman/node_modules/unirest/docs/unirest/0.3.8/module-marshals_cookies.html
[20:10:08][Step 1/2] npm ERR! fstream_path /mnt/data/buildAgent/work/57d2ff7c9840fab3/newman/lib/node_modules/newman/node_modules/unirest/docs/unirest/0.3.8/module-marshals_cookies.html
[20:10:08][Step 1/2] npm ERR! fstream_type File
[20:10:08][Step 1/2] npm ERR! fstream_class FileWriter
[20:10:08][Step 1/2] npm ERR! code ENOENT
[20:10:08][Step 1/2] npm ERR! errno 34
[20:10:08][Step 1/2] npm ERR! fstream_stack /usr/lib/node_modules/fstream/lib/writer.js:284:26
[20:10:08][Step 1/2] npm ERR! fstream_stack Object.oncomplete (fs.js:108:15)
[20:10:09][Step 1/2] npm ERR! Error: ENOENT, lstat '/mnt/data/buildAgent/work/57d2ff7c9840fab3/newman/lib/node_modules/newman/node_modules/postman_validator/node_modules/JSV/jsdoc-toolkit/java/classes/js.jar'
[20:10:09][Step 1/2] npm ERR! If you need help, you may report this log at:
[20:10:09][Step 1/2] npm ERR!     <http://github.com/isaacs/npm/issues>
[20:10:09][Step 1/2] npm ERR! or email it to:
[20:10:09][Step 1/2] npm ERR!     <npm-@googlegroups.com>
[20:10:09][Step 1/2] 
[20:10:09][Step 1/2] npm ERR! System Linux 2.6.32-504.12.2.el6.x86_64
[20:10:09][Step 1/2] npm ERR! command "node" "/usr/bin/npm" "install" "-g" "newman" "--prefix" "newman/"
[20:10:09][Step 1/2] npm ERR! cwd /mnt/data/buildAgent/work/57d2ff7c9840fab3
[20:10:09][Step 1/2] npm ERR! node -v v0.10.36
[20:10:09][Step 1/2] npm ERR! npm -v 1.3.6
[20:10:09][Step 1/2] npm ERR! path /mnt/data/buildAgent/work/57d2ff7c9840fab3/newman/lib/node_modules/newman/node_modules/postman_validator/node_modules/JSV/jsdoc-toolkit/java/classes/js.jar
[20:10:09][Step 1/2] npm ERR! fstream_path /mnt/data/buildAgent/work/57d2ff7c9840fab3/newman/lib/node_modules/newman/node_modules/postman_validator/node_modules/JSV/jsdoc-toolkit/java/classes/js.jar
[20:10:09][Step 1/2] npm ERR! fstream_type File
[20:10:09][Step 1/2] npm ERR! fstream_class FileWriter
[20:10:09][Step 1/2] npm ERR! code ENOENT
[20:10:09][Step 1/2] npm ERR! errno 34
[20:10:09][Step 1/2] npm ERR! fstream_stack /usr/lib/node_modules/fstream/lib/writer.js:284:26
[20:10:09][Step 1/2] npm ERR! fstream_stack Object.oncomplete (fs.js:108:15)
[20:10:09][Step 1/2] npm ERR! Error: ENOENT, lstat '/mnt/data/buildAgent/work/57d2ff7c9840fab3/newman/lib/node_modules/newman/node_modules/jsdom/node_modules/acorn/test/tests.js'
[20:10:09][Step 1/2] npm ERR! If you need help, you may report this log at:
[20:10:09][Step 1/2] npm ERR!     <http://github.com/isaacs/npm/issues>
[20:10:09][Step 1/2] npm ERR! or email it to:
[20:10:09][Step 1/2] npm ERR!     <npm-@googlegroups.com>
[20:10:09][Step 1/2] 
[20:10:09][Step 1/2] npm ERR! System Linux 2.6.32-504.12.2.el6.x86_64
[20:10:09][Step 1/2] npm ERR! command "node" "/usr/bin/npm" "install" "-g" "newman" "--prefix" "newman/"
[20:10:09][Step 1/2] npm ERR! cwd /mnt/data/buildAgent/work/57d2ff7c9840fab3
[20:10:09][Step 1/2] npm ERR! node -v v0.10.36
[20:10:09][Step 1/2] npm ERR! npm -v 1.3.6
[20:10:09][Step 1/2] npm ERR! path /mnt/data/buildAgent/work/57d2ff7c9840fab3/newman/lib/node_modules/newman/node_modules/jsdom/node_modules/acorn/test/tests.js
[20:10:09][Step 1/2] npm ERR! fstream_path /mnt/data/buildAgent/work/57d2ff7c9840fab3/newman/lib/node_modules/newman/node_modules/jsdom/node_modules/acorn/test/tests.js
[20:10:09][Step 1/2] npm ERR! fstream_type File
[20:10:09][Step 1/2] npm ERR! fstream_class FileWriter
[20:10:09][Step 1/2] npm ERR! code ENOENT
[20:10:09][Step 1/2] npm ERR! errno 34
[20:10:09][Step 1/2] npm ERR! fstream_stack /usr/lib/node_modules/fstream/lib/writer.js:284:26
[20:10:09][Step 1/2] npm ERR! fstream_stack Object.oncomplete (fs.js:108:15)
[20:10:10][Step 1/2] npm http 304 http://artifactory.autodesk.com/artifactory/api/npm/npm-virtual/is-property
```

**Comment by czardoz** [comment]
What version of Newman is this?
What CI server? And which Linux distribution?

The Node version you're using is very old, can you update to Node v4+ and install Newman Beta?

`npm i -g newman@beta `

Newman Beta does not depend on contextify module which seems to be causing issues here.

**Comment by czardoz** [comment]
@zonito closing this issue, feel free to reopen if you're still having issues.
