### ISSUE TITLE
newman htmlextra

### ISSUE THREAD

**Issue by semih-beki** [postmanlabs/newman#3111]
When I exported before, I was getting output as example.postman_collection. And then there was no problem? I don't know if I changed a setting or if there was an update.:

i have a collection i am running it. I export it, it gives a json blabla .postman_test_run.json found. I then run this in console .\example.postman_test_run.json -r htmlextra. And I am making error like below:

PS C:\Users\noname\Desktop\test> newman run .\Example.postman_test_run.json -r htmlextra
C:\Users\noname\node_modules\newman-reporter-htmlextra\lib\index.js:377
            default: (this.summary.collection.name).match(pattern) ?
                                                    ^

TypeError: Cannot read property 'match' of undefined
    at EventEmitter.<anonymous> (C:\Users\noname\node_modules\newman-reporter-htmlextra\lib\index.js:377:53)
    at EventEmitter.emit (C:\Users\noname\AppData\Roaming\npm\node_modules\newman\node_modules\eventemitter3\index.js:203:33)
    at done (C:\Users\noname\AppData\Roaming\npm\node_modules\newman\lib\run\index.js:314:29)
    at C:\Users\noname\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\backpack\index.js:58:34
    at PostmanCollectionRun._process (C:\Users\noname\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\runner\run.js:160:13)
    at PostmanCollectionRun.<anonymous> (C:\Users\noname\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\runner\run.js:166:76)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)

**Comment by OussamaNairi** [comment]
I face the same error

**Comment by Shivam-dev925** [comment]
+1
