### ISSUE TITLE
Parse Error encountered when running newman with --insecure parameter

### ISSUE THREAD

**Issue by jsblock78** [postmanlabs/newman#313]
I am trying to work around an issue with DEPTH_ZERO_SELF_SIGNED_CERT error happening on the request by supplying the --insecure (-k) parameter to newman. When passing this parameter I am receiving a Parse Error.

Error: Parse Error
    at CleartextStream.socketOnData (http.js:1584:20)
    at CleartextStream.read [as _read] (tls.js:514:12)
    at CleartextStream.Readable.read (_stream_readable.js:341:10)
    at EncryptedStream.write [as _write] (tls.js:369:25)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at EncryptedStream.Writable.write (_stream_writable.js:183:11)
    at write (_stream_readable.js:602:24)
    at flow (_stream_readable.js:611:7)
    at Socket.pipeOnReadable (_stream_readable.js:643:5)

**Comment by czardoz** [comment]
Are you able to make a request using Node's standard library?

**Comment by jsblock78** [comment]
It does not look like I am able to, I am getting HPE_INVALID_CONSTANT. These requests are working in Postman fine, so I am looking into Node stumbling - perhaps due to proxy or something. I am installing wireshark now to look at the response.

**Comment by czardoz** [comment]
Yep, looking at the traceback, it occurred in Node's standard library, so this is probably a Node issue.

**Comment by jsblock78** [comment]
Closing this issue then, is a Node issue.

**Comment by jsblock78** [comment]
I was able to successfully make the request using node using something similar to this:
https://gist.github.com/matthias-christen/6beb3b4dda26bd6a221d

It is definitely a byproduct of the proxy that I need to pass through - newman runs fine without the proxy. Where is newman getting proxy information from? Does it use the information from Windows (IE) setting, or is it using npm config or something similar?

**Comment by jsblock78** [comment]
And to note, this is beyond just the --insecure argument. I will receive an error either way, without the --insecure I get:

Error: SSL Error: DEPTH_ZERO_SELF_SIGNED_CERT
    at Request.onRequestResponse (C:\Users\blockje\AppData\Roaming\npm\node_modu
les\newman\node_modules\request\request.js:903:24)
    at ClientRequest.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1689:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23
)
    at CleartextStream.socketOnData [as ondata] (http.js:1584:20)
    at CleartextStream.read [as _read] (tls.js:514:12)
    at CleartextStream.Readable.read (_stream_readable.js:341:10)
    at EncryptedStream.write [as _write] (tls.js:369:25)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)

and with --insecure i get:

Error: Parse Error
    at CleartextStream.socketOnData (http.js:1584:20)
    at CleartextStream.read [as _read] (tls.js:514:12)
    at CleartextStream.Readable.read (_stream_readable.js:341:10)
    at EncryptedStream.write [as _write] (tls.js:369:25)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at EncryptedStream.Writable.write (_stream_writable.js:183:11)
    at write (_stream_readable.js:602:24)
    at flow (_stream_readable.js:611:7)
    at Socket.pipeOnReadable (_stream_readable.js:643:5)

**Comment by czardoz** [comment]
Newman internally uses the request library, which can pick up proxy configuration from environment variables, as documented in their readme: https://github.com/request/request/blob/master/README.md#proxies

Newman explicitly never passes proxy configuration to the library, so my guess is that it is being picked up from the variables.

**Comment by jsblock78** [comment]
I will try to either make a successful request or duplicate my problem using the request library then. Will update shortly.

**Comment by jsblock78** [comment]
Was able to get both Request & Newman working by populating the HTTP_PROXY and HTTPS_PROXY environment variables in Windows. It looks like some appliance was intercepting the traffic, and returning a generic "That site is blocked" error message. This appliance was not forming its certificates or headers correctly.
