### ISSUE TITLE
Getting module version mismatch error when running postman collection in newman

### ISSUE THREAD

**Issue by akapoor47** [postmanlabs/newman#376]
Getting below error when trying to run a postman collection from newman. Node Version is - v4.4.2 NPM version is - 2.15.0 Newman version is - 2.0.5

````
newman -c TPO_Regression.json
    /usr/local/lib/node_modules/newman/node_modules/jsdom/node_modules/contextify/node_modules/bindings/bindings.js:83
            throw e
            ^

    Error: Module version mismatch. Expected 46, got 14.
        at Error (native)
        at Object.Module._extensions..node (module.js:434:18)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)
        at Module.require (module.js:353:17)
        at require (internal/module.js:12:17)
        at bindings (/usr/local/lib/node_modules/newman/node_modules/jsdom/node_modules/contextify/node_modules/bindings/bindings.js:76:44)
        at Object.<anonymous> (/usr/local/lib/node_modules/newman/node_modules/jsdom/node_modules/contextify/lib/contextify.js:1:96)
        at Module._compile (module.js:409:26)
        at Object.Module._extensions..js (module.js:416:10)
````

**Comment by czardoz** [comment]
Hi, seems like you recently updated your node version. Newman v2.0.5 does not depend on contextify module which we see in the error. 

Can you try reinstalling Newman?

**Comment by czardoz** [comment]
Closing this issue now, @akapoor47 feel free to reopen if you're still facing this issue :)
