### ISSUE TITLE
Error on install OSX 10.11

### ISSUE THREAD

**Issue by wkuckro** [postmanlabs/newman#421]
`````` module.js:442
    throw err;
    ^

Error: Cannot find module 'process-nextick-args'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_readable.js:6:23)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)```

This is the error i get attempting to install. node 6.2.1
``````

**Comment by kunagpal** [comment]
@wkuckro Closing issue due to inactivity. Please revert here if your issue still persists.

**Comment by Trisha1212** [comment]
I am facing same issue

**Comment by kevin-smets** [comment]
No issues here:

```
node --version
v6.10.0

sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G1217
```

Installed node through homebrew, managing node version by using `n` so there's no sudo required for global installs, maybe that could be something?
