### ISSUE TITLE
TypeError: 'caller' and 'arguments' are restricted function properties and cannot be accessed in this context.

### ISSUE THREAD

**Issue by qrobinson** [postmanlabs/newman#424]
xxxxxx@xxxxxxx:/opt/node-v5.9.1-linux-x64/bin$ ./npm version
{ npm: '3.9.5',
  ares: '1.10.1-DEV',
  http_parser: '2.6.2',
  icu: '56.1',
  modules: '47',
  node: '5.9.1',
  openssl: '1.0.2g',
  uv: '1.8.0',
  v8: '4.6.85.31',
  zlib: '1.2.8' }

xxxxxx@xxxxxxx:/opt/node-v5.9.1-linux-x64/bin$ ./newman --version
1.3.2

>==<

xxxxxx@xxxxxxx:/opt/node-v5.9.1-linux-x64/bin$ 
./newman \
-O '/home/xxxxxx/Documents/SPS_APIs/postman/req-resp.log' \
-c '/home/xxxxxx/Documents/SPS_APIs/postman/my_collection.postman_collection.json'  \
-e '/home/xxxxxx/Documents/SPS_APIs/postman/SPS229+SAT108_Satellite.postman_environment.json' 

Iteration 1 of 1
/opt/node-v5.9.1-linux-x64/lib/node_modules/newman/src/responseHandlers/TestResponseHandler.js:210
            sugar.funcs[p] = Function.prototype[p];
                                               ^

TypeError: 'caller' and 'arguments' are restricted function properties and cannot be accessed in this context.
    at Array.<anonymous> (/opt/node-v5.9.1-linux-x64/lib/node_modules/newman/src/responseHandlers/TestResponseHandler.js:210:48)
    at arrayEach (/opt/node-v5.9.1-linux-x64/lib/node_modules/newman/node_modules/sugar/release/sugar-full.development.js:934:20)
    at Array.extend.each (/opt/node-v5.9.1-linux-x64/lib/node_modules/newman/node_modules/sugar/release/sugar-full.development.js:1815:7)
    at Object.jsface.Class._createSandboxedEnvironment (/opt/node-v5.9.1-linux-x64/lib/node_modules/newman/src/responseHandlers/TestResponseHandler.js:209:56)
    at Object.jsface.Class._runTestCases (/opt/node-v5.9.1-linux-x64/lib/node_modules/newman/src/responseHandlers/TestResponseHandler.js:51:32)
    at Object.jsface.Class._onRequestExecuted (/opt/node-v5.9.1-linux-x64/lib/node_modules/newman/src/responseHandlers/TestResponseHandler.js:38:28)
    at emitMany (events.js:126:20)
    at EventEmitter.emit (events.js:195:7)
    at Object.jsface.Class.emit (/opt/node-v5.9.1-linux-x64/lib/node_modules/newman/src/utilities/EventEmitter.js:34:22)
    at Object.<anonymous> (/opt/node-v5.9.1-linux-x64/lib/node_modules/newman/src/runners/RequestRunner.js:199:22)

**Comment by czardoz** [comment]
This is because of a version mismatch (you're probably using an older version of Node)

Check the readme for details, we have detailed instructions on installing the correct version.

**Comment by qrobinson** [comment]
node version 5.9.1 is provided in the report, as is newman 1.3.2

**Comment by czardoz** [comment]
As documented in [the readme](https://github.com/postmanlabs/newman#supported-node-versions), you need to use Newman v2.0+ (the latest is v2.1.1)
