### ISSUE TITLE
Form data with file type parameter that has an empty value throws an error

### ISSUE THREAD

**Issue by desygn** [postmanlabs/newman#586]
When using the new NodeJS module with existing postman test collections I get an error when I attempt to execute a request that has a form data file parameter with an empty value parameter.

The error "TypeError: path must be a string" is returned.

The full stack trace is:

"TypeError: path must be a string\n   
 at TypeError (native)\n    
 at Object.fs.open (fs.js:540:11)\n    
 at ReadStream.open (fs.js:1673:6)\n    
 at new ReadStream (fs.js:1660:10)\n    
 at Object.fs.createReadStream (fs.js:1608:10)\n    
 at c:\Users\Art\node_modules\newman\node_modules\postman-runtime\lib\runner\extensions\request.command.js:33:46\n    
 at c:\Users\Art\node_modules\newman\node_modules\postman-runtime\node_modules\async\dist\async.js:2333:11\n    
 at replenish (c:\Users\Art\node_modules\newman\node_modules\postman-runtime\node_modules\async\dist\async.js:872:19)\n    
 at c:\Users\Art\node_modules\newman\node_modules\postman-runtime\node_modules\async\dist\async.js:882:13\n    
 at eachOfLimit (c:\Users\Art\node_modules\newman\node_modules\postman-runtime\node_modules\async\dist\async.js:2266:24)\n    
 at c:\Users\Art\node_modules\newman\node_modules\postman-runtime\node_modules\async\dist\async.js:932:18\n    
 at Object.reduce (c:\Users\Art\node_modules\newman\node_modules\postman-runtime\node_modules\async\dist\async.js:2332:7)\n    
 at resolveFiles (c:\Users\Art\node_modules\newman\node_modules\postman-runtime\lib\runner\extensions\request.command.js:23:26)\n    
 at module.exports.process.request.async.waterfall.item.request (c:\Users\Art\node_modules\newman\node_modules\postman-runtime\lib\runner\extensions\request.command.js:116:21)\n    
 at nextTask (c:\Users\Art\node_modules\newman\node_modules\postman-runtime\node_modules\async\dist\async.js:4923:16)\n    
 at c:\Users\Art\node_modules\newman\node_modules\postman-runtime\node_modules\async\dist\async.js:4917:15\nFrom previous event:\n    
 at module.exports.tests.runRegisterAndUploadAssetTests (c:\Users\Art\Git\ci-apis\Postman.Integration.Tests\tests.js:42:27)\nFrom previous event:\n    
 at Object.<anonymous> (c:\Users\Art\Git\ci-apis\Postman.Integration.Tests\run_tests.js:7:6)\n    
 at Module._compile (module.js:409:26)\n    
 at Object.Module._extensions..js (module.js:416:10)\n    
 at Module.load (module.js:343:32)\n   
at Function.Module._load (module.js:300:12)\n    
at Module.runMain [as _onTimeout] (module.js:441:10)\n    
at Timer.listOnTimeout (timers.js:92:15)"

**Comment by desygn** [comment]
Just noticed there is another open bug for this. Sorry for the duplication!
