### ISSUE TITLE
ReferenceError in test-script on the first request of the collection while running Newman

### ISSUE THREAD

**Issue by Kriz1881** [postmanlabs/newman#722]
Hi,
We have a collection which runs with no problems in Postman. 
We also have some tests for basic validations on the response. 
When we are launching the collection with Newman, sometimes we are getting error only on the first request in the collection:  
1. Error - Invalid Protocol
2. ReferenceErr - responseBody is not defined at test-script:5:31

Here are the details:
We have a collection of 20+ HTTP (not httpS) requests with a few tests for each one of them.
From time to time we get the error reported here, but only on the first request in the collection.

We have isolated that request in a separate collection and we executed it separately during different times of the day for a few days.

We re-encountered the issue again - 3 times with the **ETIMEDOUT** Socket Error:

> \HTTP 8568: SOCKET ERROR: connect ETIMEDOUT ((server IP)):((port)) Error: connect ETIMEDOUT
>     at Object.exports._errnoException (util.js:907:11)
>     at exports._exceptionWithHostPort (util.js:930:20)
>     at TCPConnectWrap.afterConnect [as oncomplete](net.js:1077:14)
> [errored]
> HTTP 8568: CLIENT socket onClose
> HTTP 8568: removeSocket ((server IP)):((port)): destroyed: true
> HTTP 8568: HTTP socket close
>   2? ReferenceError in test-script

The last time, however, we got an **ECONNRESET** socket error:

> /HTTP 2672: SOCKET ERROR: read ECONNRESET Error: read ECONNRESET
>     at exports._errnoException (util.js:907:11)
>     at TCP.onread (net.js:557:26)
> [errored]
> HTTP 2672: CLIENT socket onClose
> HTTP 2672: removeSocket ((server IP)):((port)): destroyed: true
> HTTP 2672: HTTP socket close
>   2? ReferenceError in test-script

I am attaching the full debug logs from each occurrence.
In all of them we are using a request timeout of 1 minute, but as you can see, the errors appear after ~30 seconds.

Newman version: 3.1.2
Postman version: 4.7.2 (Windows app)
NodeJS version(s):

```
{ http_parser: '2.7.0',
  node: '4.6.0',
  v8: '4.5.103.37',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '56.1',
  modules: '46',
  openssl: '1.0.2j' } 
```

Client machine OS: Windows 7 SP1, 64bit
Server machine OS: Windows Server 2012 R2, 64bit

**PS**: We have tokenized the server IP, port and URL path in the logs for confidentiality reasons

[newman-debug-log-Reference-error-in-test-script-1-ETIMEDOUT.txt](https://github.com/postmanlabs/newman/files/547059/newman-debug-log-Reference-error-in-test-script-1-ETIMEDOUT.txt)
[newman-debug-log-Reference-error-in-test-script-2-ETIMEDOUT.txt](https://github.com/postmanlabs/newman/files/547060/newman-debug-log-Reference-error-in-test-script-2-ETIMEDOUT.txt)
[newman-debug-log-Reference-error-in-test-script-3-ETIMEDOUT.txt](https://github.com/postmanlabs/newman/files/547061/newman-debug-log-Reference-error-in-test-script-3-ETIMEDOUT.txt)
[newman-debug-log-Reference-error-in-test-script-ECONNRESET.txt](https://github.com/postmanlabs/newman/files/547062/newman-debug-log-Reference-error-in-test-script-ECONNRESET.txt)

**Comment by czardoz** [comment]
@Kriz1881 these seem to be intermittent connection issues. Can you run newman like this:

```
NODE_DEBUG=request newman run <your options>
```

And paste the log here? Feel free to strip out confidential information. You can also email us at help@getpostman.com

**Comment by kunagpal** [comment]
@Kriz1881 Closing issue due to lack of activity. Feel free to create a new issue if you're facing difficulties. Thanks! 😄
