### ISSUE TITLE
Buffer.from usage in bootcode causes failure on Node 5

### ISSUE THREAD

**Issue by itsjamie** [postmanlabs/newman#855]
bootcode.js uses Buffer.from, but engines in package.json is set to >= 4.

Supposedly Buffer.from API was added in Node 6.

We got this error in a Jenkins job.. 

```
TypeError: this is not a typed array.
    at Function.from (native)
    at module.exports (/var/lib/jenkins/jobs/snip/workspace/node_modules/postman-sandbox/.cache/bootcode.js:1:105)
    at cacher (/var/lib/jenkins/jobs/snip/workspace/node_modules/postman-sandbox/lib/bootcode.js:32:5)
    at Object.module.exports.createContext (/var/lib/jenkins/jobs/snip/workspace/node_modules/postman-sandbox/lib/index.js:108:9)
```

**Comment by shamasis** [comment]
Is it happening on Newman load itself or when a particular collection is run?

At a glance, I am unable to say what's causing the issue. However, can you check if you are passing right variables to Buffer.from?

I am delving deep behind my reasoning (I may be wrong, and will re check tomorrow):

Buffer.from should work inside sandbox in node v4 as well. This is because your code is running in a sandbox environment where everything is shimmed and emulated using browserify (check feross/buffer module that we use.) If you notice, the error says this is not a typed array instead of saying Buffer.from is undefined. The unit tests of postman-sandbox also tests these in node v4 environment.

If you can replicate this issue on a locally installed Node v4 system with a specific collection, can you share the same?

**Comment by itsjamie** [comment]
Here is the full output

```
./node_modules/.bin/newman run ./staging/staging.postman_collection.json -e ./staging/staging.postman_environment.json --ignore-redirects
/var/lib/jenkins/jobs/snip/workspace/node_modules/postman-sandbox/.cache/bootcode.js:1
(function (exports, require, module, __filename, __dirname) { module.exports=function(d){d(null, Buffer.from({"type":"Buffer","data":[114,101,113,117,105,114,101,61,40,102,117,110,99,116,105,111,110,32,101,40,116,44,110,44,114,41,123,102,117,110,99,116,105,111,110,32,115,40,111,44,117,41,123,105,102,40,33,110,91,111,93,41,123,105,102,40,33,116,91,111,93,41,123,118,97,114,32,97,61,116,121,112,101,111,102,32,114,101,113,117,105,114,101,61,61,34,102,117,110,99,116,105,111,110,34,38,38,114,101,113,117,105,114,101,59,105,102,40,33,117,38,38,97,41,114,101,116,117,114,110,32,97,40,111,44,33,48,41,59,105,102,40,105,41,114,101,116,117,114,110,32,105,40,111,44,33,48,41,59,118,97,114,32,102,61,110,101,119,32,69,114,114,111,114,40,34,67,97,110,110,111,116,32,102,105,110,100,32,109,111,100,117,108,101,32,39,34,43,111,43,34,39,34,41,59,116,104,114,111,119,32,102,46,99,111,100,101,61,34,77,79,68,85,76,69,

TypeError: this is not a typed array.
    at Function.from (native)
    at module.exports (/var/lib/jenkins/jobs/snip/workspace/node_modules/postman-sandbox/.cache/bootcode.js:1:105)
    at cacher (/var/lib/jenkins/jobs/snip/workspace/node_modules/postman-sandbox/lib/bootcode.js:32:5)
    at Object.module.exports.createContext (/var/lib/jenkins/jobs/snip/workspace/node_modules/postman-sandbox/lib/index.js:108:9)
    at PostmanCollectionRun.module.exports.init (/var/lib/jenkins/jobs/snip/workspace/node_modules/postman-runtime/lib/runner/extensions/event.command.js:68:17)
    at /var/lib/jenkins/jobs/snip/workspace/node_modules/postman-runtime/node_modules/async/dist/async.js:3828:13
    at replenish (/var/lib/jenkins/jobs/snip/workspace/node_modules/postman-runtime/node_modules/async/dist/async.js:1018:21)
    at /var/lib/jenkins/jobs/snip/workspace/node_modules/postman-runtime/node_modules/async/dist/async.js:1022:13
    at eachOfLimit (/var/lib/jenkins/jobs/snip/workspace/node_modules/postman-runtime/node_modules/async/dist/async.js:1049:26)
    at /var/lib/jenkins/jobs/snip/workspace/node_modules/postman-runtime/node_modules/async/dist/async.js:1054:20
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

I updated the job to run with Node 7.3.0 and now it is working as intended. Sorry that I can't be of more help and determine if it's the collection at this time.

**Comment by shamasis** [comment]
Oh it is definitely a bug in our end. Rushing to fix and release a patch today.

**Comment by brendo** [comment]
Also hit this one today in our Node V4 environment (AWS Lambda testing).

**Comment by thirstyfish** [comment]
Yep, same issue here.

**Comment by shamasis** [comment]
The fix isn't ready. Releasing a patch today.

**Comment by kunagpal** [comment]
@brendo @thirstyfish @itsjamie This issue has been fixed in Newman `v3.4.1`, do go ahead and check it out!

**Comment by itsjamie** [comment]
Thanks for the quick turnaround. Much appreciated!

**Comment by thirstyfish** [comment]
Thanks for your great support guys!
